site_name: STELA Toolkit
site_description: Tools for interpolating astrophysical light curves using Gaussian Processes in order to compute frequency-domain and standard time domain data products
theme:
  name: material
  extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/collinlewin/STELA-Toolkit
  favicon: assets/favicon.ico

  logo: assets/stela_logo_sq.png
  favicon: assets/stela_logo_sq.png
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - navigation.sections
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: yellow

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
          paths: [stela_toolkit]
  - mkdocs-jupyter:
      execute: False

nav:
  - Home: index.md
  - Overview: overview.md
  - Gaussian Processes: gaussian_process_intro.md
  - Installation: installation.md
  - Tutorial: tutorial.ipynb
  - Class Reference:
      - Coherence: reference/coherence.md
      - Cross Correlation: reference/cross_correlation.md
      - Cross Spectrum: reference/cross_spectrum.md
      - Data Loader: reference/data_loader.md
      - Data Simulator: reference/data_simulator.md
      - Gaussian Process: reference/gaussian_process.md
      - Lag Energy Spectrum: reference/lag_energy_spectrum.md
      - Lag Frequency Spectrum: reference/lag_frequency_spectrum.md
      - Power Spectrum: reference/power_spectrum.md
      - Preprocessing: reference/preprocessing.md
      - Internal:
          - Frequency Binning: reference/frequency_binning.md
          - Plotting: reference/plot.md
          - _CheckInputs: reference/check_inputs.md
          - _ClearWarnings: reference/clarify_warnings.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.details

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/custom.css